### ISSUE TITLE
Offering Specific Versions?

### ISSUE THREAD

**Issue by playmer** [a7ex/homebrew-formulae#2]
Hi there, we use xcresultparser at work and have found that for now we'd like to pin on a specific version at times. Right now we've switched to downloading and installing it directly, but I figured we should see if you'd be willing to host specific versions in your tap.

I've spent some time on-and-off writing a generator for the formulae files, and I think it's nearly there, just need to figure out how brew decides what the "default" package is, and some config changes based on [suggestions from homebrew](https://docs.brew.sh/Versions).

Here's what it looks like currently: https://github.com/playmer/homebrew-formulae/

Right now it's generating a formula for every release of each package, but I can trim it down to latest minor release as homebrew recommends.

That all said, I don't want to be presumptuous, hence why I opened an issue rather than a PR. We can always host our own tap for this internally, but I thought it would be better to see what your thoughts were.

Either way, really appreciate your work!

**Comment by a7ex** [comment]
I am all up for it!
I haven't had thought of it, because I always use the latest versions of the tools and therefore didn't have the need to pin a version, but I understand the benefits.
For me it would just mean, that instead of changing the homebrew formulae, I would just duplicate it into a new one for every version?
What are the downsides? Does the consumer require any special setting on his/her end?

**Comment by playmer** [comment]
Well if you were to use the generator then it should just generate all the files for you every time. It goes and downloads every non-prerelease release, computes the sha, and generates the formulae files. 

Right now the downside is that I can't figure out how to correctly make a "latest" or "default" version. So if you just do `brew install xcresultparser` it won't know what to do, rather than do what it does currently which is install the latest. I think maybe I can just make a dupe and not have the version in the name/class and that might work? It just doesn't seem to be what they do with python for example which seems to only have versioned formulae. 

As far as downsides, I don't _think_ it should have any once I solve the above. But that said I'm not a brew expert, just a tooling person encountering this need for the first time 😀

**Comment by a7ex** [comment]
Why do I need to generate all files every time? Do they differ every time? I thought adding one file for a new version (instead of editing the only file, which is what I do now) would be sufficient?
As you notice, I am not a brew expert as well :-)
But yes, you are right, the ability to use `brew install xcresultparser` without any version number in order to get the latest, is indeed crucial. We do not want to change our build chain scripts every time there is a minor update. Ideally it would be like it is in SPM, so we could define upToNextMajor, or in cocoapods with the ~ notation. That would be the most useful for build chains.
But in case of these 3 tools, there hasn't been the need for it, as I try to be always backward compatible.

**Comment by playmer** [comment]
I'll work on getting the default bit working tomorrow, I have no desire to break that behavior 😀

Regarding regenerating everything, it was purely just a matter of it being easier to implement while I was trying to hammer out the versioned files. I can check to see if we already have a version file, and if we do skip it. That way it would only generate new versions, and probably the latest version, since I'd have to otherwise try to parse it to figure out what it had. 

As far as specifying the version it should just be `brew install xcresultparser@1.6.5` for example to get a specific version. And that should be able to be used in a requirements.txt as well. Alternatively like mentioned above, omitting the @version for the latest, just like it is now. 

One other note is that I ran into a slight pickle with findsimulator being a little hard to generate given that you check the version specifically. So the generator is a little hacky around that, could be unfortunate if there's another way to assert in the future that isn't a static string or generated version number.

**Comment by a7ex** [comment]
Yes the line
`assert_match "0.3", shell_output("#{bin}/findsimulator -v")`

checks for the specific version. I already changed that in case of xcresultparser, as the test is just to check whether the compilation was successful. That was the easiest test to check, whether the app compiled. I can come up with something else.

**Comment by a7ex** [comment]
Thank you so much for the improvement!

**Comment by playmer** [comment]
No worries! Although something I realized this morning is that there was an obvious solution to a problem I mentioned in the PR: "The only caveat I can think of might be if you release a new patch release for an older minor release: it won't proactively delete the old patch version, that would need to be manual."

I probably should've made the versions we supply named based on the major.minor release, rather than major.minor.patch. That way we could just update the relevant major.minor file if there's a newer patch. Although it does make "generating everything" the easier solution again, otherwise we'd have to parse the files to know what actual version they represent rather than just the file name.

Any thoughts on this? Or should we leave it and not delete old patch releases in the case of needing to make a new one?

**Comment by a7ex** [comment]
I'd say, that we can leave it as it is for now. If we (or someone else) encounter any problems, we can still change. I think the current implementation allows to make a file for even patches, if one day needed. And we can also just leave the patch version, we have now and create a new file for the next patch, if we want/need it. I think, as it is now it provides more flexibility. If we go for only major.minor and later find out, that we would like to distinguish patch version, for what reason ever, it will be more difficult. As I said earlier, the tools are simple and thus it's fairly easy to not introduce breaking changes.

But yes, I can only say that, because as of now, xcresultKit is using the --legacy flag with Apple's xcresulttool, which indeed introduced a breaking change with Xcode 16 :-)

So you never know and therefore it is better to use the more flexible approach, as you have it now.
